### PR TITLE
Add Clover to Productivity

### PR DESCRIPTION
**Pull request by bektigalan**

### CODE REVIEW

**Comment by Rictusempra** [comment]
@bektigalan Are you aware that latest version has built-in invasive ads?

**Comment by bektigalan** [comment]
@Rictusempra Oh, yes, i am sorry, i use earlier version, so i didn't know, i just check it in my virtual machine, it does have ads, version 3.3

**Comment by bektigalan** [comment]
@Rictusempra do i need to delete it or just change the type of software? i am sorry, it's my first time contribute to something

**Comment by Rictusempra** [comment]
Maybe leave this open and let @rahulkapoor90 to decide. If you need any alternative, I personally suggest QTTabBar

**Comment by rahulkapoor90** [comment]
Yes. Can't add clover if it has built-in invasive ads now. Thanks @Rictusempra for handling this issue.

**Pull request closed without merging**
