### PR TITLE
Remove Tower as it's a MacOS only app and furthermore the link wasn't…

### PR DESCRIPTION
**Pull request by brianjking**
… even going to the Tower Git App

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
@RiseLedger  should we remove tower?

**Comment by RiseLedger** [comment]
@rahulkapoor90 Yes, I think we should remove it.

@brianjking Please rebase your fork to have the latest changes from our repo. Right now I can not merge PR because of branch conflicts.

https://www.dropbox.com/s/pt7z938jyu250u8/Screenshot%202016-06-11%2007.45.44.png?dl=0

Thanks

**Comment by rahulkapoor90** [comment]
@RiseLedger i also think we should add awesome lists for windows comands and screensavers(if needed) just like there are for osx under our organization.

**Comment by RiseLedger** [comment]
@rahulkapoor90 With windows commands - are you referring to keyboard shortcuts or what exactly do you mean?

**Comment by rahulkapoor90** [comment]
- @RiseLedger like this https://github.com/herrbischoff/awesome-osx-command-line

**Comment by brianjking** [comment]
See #9

**Pull request closed without merging**
