### PR TITLE
Please dont be biased. Atleast internet and knowlege is neutral, dont politicize with flag and language for groups of people

### PR DESCRIPTION
**Pull request by mohanbabubb**
Please dont be biased. Atleast internet and knowlege is neutral, dont politicize with flag and language for groups of people

### CODE REVIEW

**Comment by notlmn** [comment]
Don't politicise everything you see, even when it isn't.

Providing some text in other languages is called translating, not politicising.

------

> dont politicize with flag and language for groups of people

FYI, English is a language.

------

> Please dont be biased.

Choosing English over other languages can also be considered "bias" by your own explanation.

**Comment by mohanbabubb** [comment]
yeah agree, that english is language.. why cannot you put other major spoke languages in world. ? why just chinese.?

**Comment by mohanbabubb** [comment]
never mind. people dont understand unless they are hurt personally. sorry for being emotional.

**Comment by notlmn** [comment]
> yeah agree, that english is language.. why cannot you put other major written languages in world. ? why just chinese.?

You're free to contribute in any other language, if you can. That's how this works.

**Pull request closed without merging**
