### PR TITLE
Add WACUP

### PR DESCRIPTION
**Pull request by The1Freeman**
WACUP is a project that aims to improve the overall Winamp experience by providing features and bugfixes to issues pertaining to Winamp 5.666.
More information can be found at https://getwacup.com/

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
Sorry, not that useful. Closed.

**Comment by The1Freeman** [comment]
Can you state a reason as to why it's not that useful?

**Comment by Dr-Flay** [comment]
Considering you have Winamp in the list, and WACUP has more features and is still maintained and bugs fixed, why opt for the lesser of the 2 with no future and has bugs that will never be fixed ?
WACUP comes with support for the most common streaming media sites. It supports more formats inc. Opus, FLAC, APE.
It even supports discord and twitter notifications.

Please explain why Winamp is more useful ?

**Comment by mveroukis** [comment]
@rafamoreira You should reconsider. Winamp is in the past, WACUP is the future. We can go into this in detail if you like. It's worth considering.

**Comment by The1Freeman** [comment]
It's been almost 2 weeks since it got denied for no real reason, and I guess that we shouldn't expect a response from @rahulkapoor90, despite being active in this repository, having commited and merged a pull request 3 days ago.

It's sad that when trying to engage into the open source community (which is managed by only **_one_** person) by trying to commit something useful, it gets shut down with no real explanation.

**Comment by rahulkapoor90** [comment]
Hi Guys,

I haven’t forgot about this thing. Apologies, from my side  as i have been really busy with work. I really want to support your contribution and will definitely check this tool by tonight and get back with response. Cheers!

**Comment by rahulkapoor90** [comment]
I've actually just completed testing the product extensively. It's definitely maintained and good addition to this repository. I've added. thanks @The1Freeman 👍

**Comment by The1Freeman** [comment]
Thank you so much!
I'm happy we were able to solve this after all :)

**Comment by Dr-Flay** [comment]
Onwards and upwards

**Pull request merged**
