### PR TITLE
Add 7+ Taskbar Tweaker to Customization section

### PR DESCRIPTION
**Pull request by mdonatas**
This tiny and efficient utility has many customization options such as "not grouping taskbar buttons", controlling volume with mouse scroll over clock area, or middle-click to close open apps on the taskbar (similar to how one can close tabs in browsers or text documents in various editors).

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
Would have to test it first. Will get back to this soon.

**Comment by mdonatas** [comment]
Sure! I myself can't live without "don't group buttons" feature which allows to "sort" open apps in any way. By default Windows glues buttons by process and you wouldn't be able to have explorer.exe firefox.exe explorer.exe like so:
image

Then there is middle-click to close which if you use in app with tab makes a lot of sense on a taskbar.

There are quite some more other options which I don't use but they open a lot of possibilities to those who don't like some tiny bit about the taskbar.

**Comment by devployment** [comment]
I'd like to promote this tool as well. One "killer feature" for me is, that I'm able to ungroup and get rid of the name as well. But to have this it's a bit strange to configure. Task Bar grouping has to be enabled, and then be disabled by this tool. But then you can have something like this. Best ob all worlds. 

Not grouped, small icons, draggable and no text :)

image

**Comment by mdonatas** [comment]
Just solved a merge conflict via github, if you'd rather want it rebased I could do that too.

**Comment by rahulkapoor90** [comment]
Merged thanks!

**Pull request merged**
